server:
  port: 8080

spring:
  application:
    name: backend-study
  profiles:
    active: local
  datasource:
    backend:
      jpa:
        leader:
          pool-name: backend-leader-hikari-pool
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://localhost:3307/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
          connection-test-query: SELECT 1
          username: root
          password: backend
        follower:
          pool-name: backend-follower-hikari-pool
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://localhost:3307/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
          connection-test-query: SELECT 1
          username: read_user
          password: readonly
          read-only: true
      r2dbc:
        leader:
          protocol: mariadb
          host: localhost
          port: 3307
          database: shop
          username: root
          password: backend
          pool:
            name: backend-leader-r2dbc-pool
            initial-size: 2
            max-size: 5
            max-idle-time: 10
            validation-query: SELECT 1
        follower:
          protocol: mariadb
          host: localhost
          port: 3307
          database: shop
          username: read_user
          password: readonly
          pool:
            name: backend-follower-r2dbc-pool
            initial-size: 2
            max-size: 5
            max-idle-time: 10
            validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true
#    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDBDialect