version: '3'
services:
  mariadb-container-master:
    image: mariadb:latest
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./master/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=backend
  mariadb-container-slave:
    image: mariadb:latest
    restart: always
    ports:
      - '3308:3306'
    volumes:
      - ./slave/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./slave/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=backend
    depends_on:
      - mariadb-container-master